### ISSUE TITLE
nodejs-rest api - sign-in error returns 200 response

### ISSUE THREAD

**Issue by townofdon** [chiedolabs/blog-app-in-many-stacks#13]
Signing in with improper credentials (wrong email address or wrong password) returns the correct error object, but the improper response.

For example: username: `blahblahsomestuff`
password: `thisisgoingtofail`

currently returns: `200 OK`
should return `400 Bad Request`

**Comment by chiedo** [comment]
Please assign to Eric!

On Wednesday, January 20, 2016, Don Juan Javier <notifications@github.com>
wrote:

> Signing in with improper credentials (wrong email address or wrong
> password) returns the correct error object, but the improper response
>
> For example: username: blahblahsomestuff
> password: thisisgoingtofail
>
> currently returns: 200 OK
> should return 400 Bad Request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chiedolabs/blog-app-in-many-stacks/issues/13>.
>


-- 
- Sent via mobile

**Comment by townofdon** [comment]
@chiedo I believe I did!

**Comment by chiedo** [comment]
Also please test for both rails-rest and nodejs-rest moving forward and
report of the bug is in one or both :)

On Wednesday, January 20, 2016, Chiedo <chiedo@chie.do> wrote:

> Please assign to Eric!
>
> On Wednesday, January 20, 2016, Don Juan Javier <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Signing in with improper credentials (wrong email address or wrong
>> password) returns the correct error object, but the improper response
>>
>> For example: username: blahblahsomestuff
>> password: thisisgoingtofail
>>
>> currently returns: 200 OK
>> should return 400 Bad Request
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/chiedolabs/blog-app-in-many-stacks/issues/13>.
>>
>
>
> --
> - Sent via mobile
>


-- 
- Sent via mobile

**Comment by townofdon** [comment]
Will do, however, the title indicates which back-end we're dealing with

**Comment by chiedo** [comment]
Perfect!
What I mean though is test both whenever you find a bug and let us know the
status of both

On Wednesday, January 20, 2016, Don Juan Javier <notifications@github.com>
wrote:

> Will do, however, the title indicates which back-end we're dealing with
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chiedolabs/blog-app-in-many-stacks/issues/13#issuecomment-173359023>
> .
>


-- 
- Sent via mobile

**Comment by townofdon** [comment]
Will do!

**Comment by townofdon** [comment]
@eduvon0220 I will work on this to try and figure out the bug!

**Comment by townofdon** [comment]
Fixed this issue by adding `res.status(400)` to response json.
