### ISSUE TITLE
update user - nodejs-rest api issue

### ISSUE THREAD

**Issue by townofdon** [chiedolabs/blog-app-in-many-stacks#15]
Tried the following request using the nodejs-rest api (rails-rest needs CORS updated to test):
`/users/:id`
`put`
`{
  "user": {
    "name": "cool"
  }
}`

It successfully updated, but is missing return data (should also include id, date created, and date modified).

This is the response received:
`{
  "user": {
    "name": "Cool",
    "email": "test@test.com",
    "username": "test"
  },
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1NjM0ZDQ3NjAwNjZiZTAxNmJmMTBjOWEiLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJwYXNzd29yZCI6IiQyYSQwOCRWZklkZXpua200ZWJMdGxvU0hpRXFPMjZSVGtHU2pSb0xFSS5tQi9Fa01QdC81amlwSVMxZSJ9.-4Ok9dHF4nx6GkQd-yL3DIDLfx6knodgVJNI-QbR-Yk"
}`

**Comment by eduvon0220** [comment]
@townofdon this should be fixed now, be sure to create a new user before testing it out for first time
