### ISSUE TITLE
Reducers shouldn't have side effects

### ISSUE THREAD

**Issue by gaearon** [chiedolabs/blog-app-in-many-stacks#25]
I see that you have some `storage.put()` calls in the reducers. This is contrary to how Redux apps should work. If you need to perform effect, you can do it before emitting an action (e.g. in a thunk action creator), or in a store subscriber. Reducers should stay pure.

**Comment by chiedo** [comment]
Fixed!
Nice catch. The redux-react-rest branch is still very much a work in progress also. I'm looking at a lot of the code and it's already looking old compared to some of the better redux work we've done for clients recently haha.

Once we have more time to finish it and refine it, we'll merge it into master.
