### ISSUE TITLE
API docs does not correctly document the create-comment endpoint

### ISSUE THREAD

**Issue by townofdon** [chiedolabs/blog-app-in-many-stacks#26]
This is in the general REST docs.

Looks like there are two endpoints in the docs for get-comment. One of them actually gets a comment, the other is meant to be the create-comment endpoint, methinks.

The following endpoint in the doc needs to be updated to be POST instead of GET:
`/posts/:post_id/comments` - Get Comment

**Comment by chiedo** [comment]
Fixed in master!
