### ISSUE TITLE
nodejs-rest api inconsistencies

### ISSUE THREAD

**Issue by townofdon** [chiedolabs/blog-app-in-many-stacks#6]
The post tags are inconsistent the way they are returned from the API:
/back-ends/nodejs-rest

Get all posts - `/posts`
returns an array of posts, each with an array of tag objects
- documentation needs to be updated - returns an array of objects for tags, not string of ids

Get a post by tag - `/tags/:tag_id/posts`
returns an array of posts, each with an array of tag id strings
- this should return an array of tag objects for each post
- documentation needs to be updated

**Comment by chiedo** [comment]
Documentation actually looks good. You were probably looking at an old version. Always use this link to see the latest version of the docs in case you have forgotten to do a git pull locally.

https://rawgit.com/chiedolabs/blog-app-in-many-stacks/master/back-ends/api-resources/rest/build/index.html#postsid.

Getting @eduvon0220 to fix the implementation in /back-ends/nodejs-rest and also potentially back-ends/rails-rest

**Comment by eduvon0220** [comment]
@chiedo In this commit 6985c5d5901c41937fc020f42652969009f6cf6d you removed `render_not_found` and `set_user` from the base_controller, but both of these methods are being called in posts_controller.  Did you do that purposefully?

**Comment by chiedo** [comment]
Hey @eduvon0220, 
I didn't actually develop that. @rfearing did.

**Comment by chiedo** [comment]
@rfearing built the Rails-rest work.
