### ISSUE TITLE
API - get user by username does not return the id, per API specs

### ISSUE THREAD

**Issue by townofdon** [chiedolabs/blog-app-in-many-stacks#9]
the following api call:
`http://localhost:8000/users?username=test`
should return a user object that contains the user id. It does not.

I ran this test in Postman, and this was after I pulled the latest changes into my git repo.

Not sure whom to assign, so I assigned @chiedo .

**Comment by chiedo** [comment]
Is this the case for both Rails and Node or just one or the other @townofdon ?

**Comment by chiedo** [comment]
Also, what does it return? 

Thanks!

**Comment by chiedo** [comment]
Lastly, @townofdon make @eduvon0220 the default assignee for future bugs!

**Comment by townofdon** [comment]
The backend was nodejs-rest. I haven't tested the rails-rest api yet.

the return object was as follows:
`{
  "user": {
    "name": "Bruce Wayne",
    "email": "test@test.com",
    "username": "test"
  }
}`

**Comment by chiedo** [comment]
Awesome! Will be an easy fix. Can you please test Rails and let @eduvon0220 if that needs to be fixed also?

**Comment by townofdon** [comment]
Making myself a JIRA task now!




*Don Townsend*
*Freelance Pianist & Songwriter*
*Web Developer - *Chiedo Labs <http://labs.chie.do/>
*Music Director - **Church of the Incarnation* <http://theincarnation.org/>
James Madison University - School of Music 2008
540-355-6473

**Comment by chiedo** [comment]
Should be resolved on nodejs-rest @townofdon
